### ISSUE TITLE
Manual option for selecting my city

### ISSUE THREAD

**Issue by HalfBloodprinc3** [tortamque/Weathque#10]
The app works very smoothly. But I can only see Paris, New York and Sydney. Please put a function to add cities manually. A search option to find my City.

**Comment by pablo03v** [comment]
I would love that too. The app looks very good but it's unusable that way

**Comment by tortamque** [comment]
> Please put a function to add cities manually. A search option to find my City.

Great idea. Has been marked for planning

**Comment by tortamque** [comment]
> The app works very smoothly. But I can only see Paris, New York and Sydney. Please put a function to add cities manually. A search option to find my City.

I am pleased to announce that the new version has already been released. You can download the updated app from the ["Releases" tab](https://github.com/tortamque/Weathque/releases/tag/1.1)
Feel free to open a new issue if you find a bug or have new ideas! :D
Thank you for your support ❤️

**Comment by pablo03v** [comment]
Awesome :) Can be closed then I guess
