### ISSUE TITLE
versionCode not increased

### ISSUE THREAD

**Issue by IzzySoft** [tortamque/Weathque#14]
Please remember to increase `versionCode` whenever making a new release – or those having your app installed won't receive update notifications (as Android uses this to tell versions apart). It is [still set to `1`](https://github.com/tortamque/Weathque/blob/main/pubspec.yaml#L19) (the part following the `+`). Thanks for taking care!

**Comment by tortamque** [comment]
Thanks for the advice! I'll fix it now

**Comment by IzzySoft** [comment]
Great, thanks for the quick action! Useless reminder: please remember for future releases, too :see_no_evil:
