### ISSUE TITLE
Certificate issue

### ISSUE THREAD

**Issue by IzzySoft** [tortamque/Weathque#17]
A scan ([see here](https://gitlab.com/IzzyOnDroid/repo/-/issues/477) for details and background) just revealed the APKs at your releases are signed using a debug key. As that has security implications, may I ask you to please switch to a proper release key, and provide the corresponding APK signed with it? Thanks in advance!

**Comment by tortamque** [comment]
Oh, yes, you're right. My APK was signed using the debug key. I'll re-sign it now. Thank you for your feedback! 😃

**Comment by tortamque** [comment]
The APK has been re-signed with a new key. Feel free to open a new issue if you have any ideas. ❤️

**Comment by IzzySoft** [comment]
As you ask for, maybe 2 things: due to the change of the signing key, those already using your app need to uninstall and re-install anyway. Maybe you want to take that chance and adjust the `packageName`/`applicationId`? The `com.example.*` space is intended for local testing. It's not a deal breaker for my repo, but it would be one for PlayStore for example.

I wait your answer on that before pulling the update in, just in case. I've no problem staying with `com.example.*` – but this would be a too good chance to miss out, what do you think? maybe `tortamque.weathque`, or `vlad.weathque`? Just let me know – and I either wait until you've switched, or take the current one if you want to stay with `com.eample.*`.

Another thing my scanner sees:

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

That's only useful for PlayStore, and you can easily get rid of it if you want:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

**Comment by IzzySoft** [comment]
Just wondering, @tortamque: are you going to rename the `applicationId` – or do you want to stay with `com.example.*`? Asking as my updater again threw an error because I didn't yet allow the new signing key (makes no sense to have everyone uninstall/reinstall multiple times). So please let me know if you want me to go with the current APK or not. I can switch over easily, I'm just waiting for you to decide.

**Comment by tortamque** [comment]
> Just wondering, @tortamque: are you going to rename the `applicationId` – or do you want to stay with `com.example.*`? Asking as my updater again threw an error because I didn't yet allow the new signing key (makes no sense to have everyone uninstall/reinstall multiple times). So please let me know if you want me to go with the current APK or not. I can switch over easily, I'm just waiting for you to decide.

Hey, yeah, I'll fix it tomorrow. I've been quite busy lately 😅

**Comment by IzzySoft** [comment]
> Hey, yeah, I'll fix it tomorrow.

Thanks!

> I've been quite busy lately 😅

Ask me! :rofl:

**Comment by tortamque** [comment]
Done! The package name has been changed to _com.tortamque.weathque_
Thank you for your tips! (If I don't respond for a long time, please ping me again 😅)
Feel free to reach out to me again anytime. I appreciate it!

Here is the link to the new release:
https://github.com/tortamque/Weathque/releases/tag/1.1.3

**Comment by IzzySoft** [comment]
Gna, another notification that didn't reach me (from your comment; I just got the one for the issue being closed)… Checking now…

```
SigningBlock blobs:
-------------------
0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
```

Not a stopper here, just a notice – and easy to get rid of. Repeating from above:

```gradle
android {
    dependenciesInfo {
        // Disables dependency metadata when building APKs.
        includeInApk = false
        // Disables dependency metadata when building Android App Bundles.
        includeInBundle = false
    }
}
```

For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.

But then, what happened to the signature you already had fixed? This APK again is signed using a debug key:

```
Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
Signer #1 certificate SHA-256 digest: b09af2209b46865b702ece6b0b85e9456029b30212cd81852cf6b1335a0998bd
Signer #1 certificate SHA-1 digest: 68d7c21331d0d91401fa0e2561a5bd4085ad2c71
Signer #1 certificate MD5 digest: c10003a16eeca48df16fb950c9253f7a
Signer #1 key algorithm: RSA
Signer #1 key size (bits): 2048
```

which **is** a stopper :cry:

**Comment by tortamque** [comment]
> Gna, another notification that didn't reach me (from your comment; I just got the one for the issue being closed)… Checking now…
> 
> ```
> SigningBlock blobs:
> -------------------
> 0x504b4453 (DEPENDENCY_INFO_BLOCK; GOOGLE)
> ```
> 
> Not a stopper here, just a notice – and easy to get rid of. Repeating from above:
> 
> ```gradle
> android {
>     dependenciesInfo {
>         // Disables dependency metadata when building APKs.
>         includeInApk = false
>         // Disables dependency metadata when building Android App Bundles.
>         includeInBundle = false
>     }
> }
> ```
> 
> For some background: that BLOB is supposed to be just a binary representation of your app's dependency tree. But as it's encrypted with a public key belonging to Google, only Google can read it – and nobody else can even verify what it really contains.
> 
> But then, what happened to the signature you already had fixed? This APK again is signed using a debug key:
> 
> ```
> Signer #1 certificate DN: C=US, O=Android, CN=Android Debug
> Signer #1 certificate SHA-256 digest: b09af2209b46865b702ece6b0b85e9456029b30212cd81852cf6b1335a0998bd
> Signer #1 certificate SHA-1 digest: 68d7c21331d0d91401fa0e2561a5bd4085ad2c71
> Signer #1 certificate MD5 digest: c10003a16eeca48df16fb950c9253f7a
> Signer #1 key algorithm: RSA
> Signer #1 key size (bits): 2048
> ```
> 
> which **is** a stopper :cry:

I will investigate this on the weekend
Sorry for long response, I'm a bit busy now with work ans university 🥲
Thank you!

**Comment by IzzySoft** [comment]
Apologies for seeming to press, @tortamque – but end of this month remaining APKs signed with debug keys are supposed to be removed. Do we have a "proper APK" until then – at least with the correct package name and signature? If that blob then gets fixed with a later release, that's OK (though the fix is pretty easy and straight forward).

**Comment by IzzySoft** [comment]
Hurts me to do this, but time's up; I'll now have to remove the app from my repo. Can of course be relisted any time later once you have it ready, please give me a ping then!

**Comment by IzzySoft** [comment]
I see you've marked the issue completed, but there's no new release. Will there be a fixed one, and will you give me a ping then?
